"""empty message

Revision ID: 8f5f0950d4e1
Revises: 
Create Date: 2020-07-25 00:10:09.609430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5f0950d4e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('firs_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('date_of_join', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Student_email'), 'Student', ['email'], unique=True)
    op.create_index(op.f('ix_Student_username'), 'Student', ['username'], unique=True)
    op.create_table('mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firs_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('date_of_join', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('is_prime', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_email'), 'mentor', ['email'], unique=True)
    op.create_index(op.f('ix_mentor_username'), 'mentor', ['username'], unique=True)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('skill_id', 'mentor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    op.drop_table('skill')
    op.drop_index(op.f('ix_mentor_username'), table_name='mentor')
    op.drop_index(op.f('ix_mentor_email'), table_name='mentor')
    op.drop_table('mentor')
    op.drop_index(op.f('ix_Student_username'), table_name='Student')
    op.drop_index(op.f('ix_Student_email'), table_name='Student')
    op.drop_table('Student')
    # ### end Alembic commands ###
